### ISSUE TITLE
Support other DB engines like Replicated

### ISSUE THREAD

**Issue by aimfeld** [VVVi/clickhouse-migrations#13]
We need to create our DB on cluster with the replicated DB engine like this: `CREATE DATABASE IF NOT EXISTS shared ON CLUSTER default ENGINE = Replicated('/clickhouse/tables/{shard}/shared', '{shard}', '{replica}');`

Currently, the [DB is created with the Atomic engine](https://github.com/VVVi/clickhouse-migrations/blob/main/src/migrate.ts#L35), and there's a todo to make it configurable which would help us.

**Comment by VVVi** [comment]
In the v1.0.0 version is added option --db-engine (or env var CH_MIGRATIONS_DB_ENGINE).
So the option can be used as: -db-engine="ON CLUSTER default ENGINE = Replicated('/clickhouse/tables/{shard}/shared', '{shard}', '{replica}')".
I am closing the issue, please feel free to reopen it if needed.
