### ISSUE TITLE
Does this tool support Replicated Merge Tree Table Engine?

### ISSUE THREAD

**Issue by hueiyuan** [VVVi/clickhouse-migrations#8]
### Description
As a title of this issue, Does this tool support Replicated Merge Tree Table Engine?
We are finding the proper opersource tool to manage our schema on clickhouse cluster.

**Comment by VVVi** [comment]
Yes, it can be provided in migration files. I have updated README.md with a more detailed example. 
If you need to provide database engine type, please check the new --db-engine option.
For now, I close the issue, feel free to reopen it if needed.
